### ISSUE TITLE
メール認証が機能していない

### ISSUE THREAD

**Issue by sudame** [chiemi627/personal_ywt#1]
## Summary
メールアドレスを認証しなくてもログインできてしまう。

## Environment

- Android 9.0
- FireFox 68.1.1

## Steps to Reproduce

1. アカウントを作成する
2. 各フォームを埋める
3. 「メールを送信しました」と出るが、メールは来ていない
4. ログインボタンを押し、ログインページに進む
5. 先ほど登録した内容でログインできる

## Problem

- 学籍番号さえ知っていれば他の学生の振り返りを公開できてしまう

## Solution

- 登録したメールアドレスにメールを送信し、リンクを踏ませることでメールアドレスを所有していることを確認する。

## Memo

せっかくなのでなにか書いてみました

**Comment by chiemi627** [comment]
うぉ!それはやばい... orz

**Comment by chiemi627** [comment]
人の振り返りが勝手に見れる問題は一応応急処置をしました。ありがとう！
メールが送れてない件はSendGridで送信は確認してるんだけど...なぜだろう。
引き続き検討します〜！

**Comment by sudame** [comment]
対応ありがとうございます🙏

## 認証の件
メールに書いてあるURLを踏まなければアカウントが有効化されない挙動を確認しました！

## メールの件
迷惑メールフォルダを確認し忘れておりました。迷惑メールフォルダを開いたところ、昨日のぶんも含めて2件着信しておりました。
人によるかもしれませんが、sXXXXXXX@s.tsukuba.ac.jp アドレスの人は自動で迷惑メールに振り分けられているかもしれません。
